dbtest:
  image: mysql:5.6
  environment:
        - MYSQL_PASS=kc123456
  expose:
        - 3306
  ports:
        - 3308:3306
  volumes:
        - /home/qiang/vboxshare/server_log/mysql56_log:/var/log/mysql
        - /home/qiang/vboxshare/server_data/mysql56_db:/data
